BaseURL: "/"
LanguageCode: "en-us"
Title: "Sohan's Blog"
theme: "sohan-light-cards"
pluralizeListTitles: false
SectionPagesMenu: "main"
disqusShortname: "sohansblog"


Params:
  Author: "Sohan Chowdhury"
  Birth: "Mon, Jul 8, 1996"
#  DateForm: "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID: "UA-73459303-1"
#  GravatarHash: "Your Hash."
  Facebook: "http://facebook.com/sifat3d"
  Twitter: "http://twitter.com/iamsohan"
  Github: "http://github.com/SohanChy"
  Disqus: "sohansblog"
  SyntaxHighlightTheme: "default.min.css"
  ShowRelatedPost: True
  ShowTagCloud: True

copyright : "&copy; 2016 Sohan Chowdhury, all rights reserved."
canonifyurls: true
paginate: 10

Taxonomies:
  tags: "tags"
