copyright = "&copy; 2016 Sohan Chowdhury, all rights reserved."
canonifyurls = "true"
SectionPagesMenu = "main"
paginate = "10"
Title = "Sohan's Blog"
LanguageCode = "en-us"
disqusShortname = "sohansblog"
pluralizeListTitles = "false"
theme = "sohan-light-cards"
BaseURL = "/"

[Taxonomies]
tags = "tags"

[Params]
SyntaxHighlightTheme = "default.min.css"
Github = "http://github.com/SohanChy"
ShowTagCloud = "true"
Disqus = "sohansblog"
Twitter = "http://twitter.com/iamsohan"
Author = "Sohan Chowdhury"
Birth = "Mon, Jul 8, 1996"
Facebook = "http://facebook.com/sifat3d"
ShowRelatedPost = "true"
GoogleAnalyticsUserID = "UA-37749531-5"
